version: '3.7' 
services:
    react-nginx-app:
      stdin_open: true
      build: 
        context: .
        dockerfile: Dockerfile
      expose:
        - "3000"
      ports:
        - "3000:3000"
      environment:
        - NODE_ENV=development